// Code generated by the codec package. DO NOT EDIT.

package somepkg

import (
	"github.com/jba/codec"
	"time"
)

type time_Time_codec struct{}

func (c time_Time_codec) Init() {}

func (c time_Time_codec) Encode(e *codec.Encoder, x interface{}) { c.encode(e, x.(time.Time)) }

func (c time_Time_codec) encode(e *codec.Encoder, m time.Time) {
	data, err := m.MarshalBinary()
	if err != nil {
		e.Fail(err)
	}
	e.EncodeBytes(data)
}

func (c time_Time_codec) Decode(d *codec.Decoder) interface{} {
	var x time.Time
	c.decode(d, &x)
	return x
}

func (c time_Time_codec) decode(d *codec.Decoder, p *time.Time) {
	data := d.DecodeBytes()
	if err := p.UnmarshalBinary(data); err != nil {
		d.Fail(err)
	}
}

func init() { codec.Register(*new(time.Time), time_Time_codec{}) }
