// Code generated by the codec package. DO NOT EDIT.

package somepkg

import (
	"github.com/jba/codec"
	"github.com/jba/codec/codecapi"
)

type codec_definedMap_codec struct{}

func (c codec_definedMap_codec) Init() {}

func (c codec_definedMap_codec) Encode(e *codecapi.Encoder, x interface{}) {
	c.encode(e, x.(codec.definedMap))
}

func (c codec_definedMap_codec) encode(e *codecapi.Encoder, m codec.definedMap) {
	if m == nil {
		e.EncodeNil()
		return
	}
	e.StartList(2 * len(m))
	for k, v := range m {
		e.EncodeString(k)
		e.EncodeBool(v)
	}
}

func (c codec_definedMap_codec) Decode(d *codecapi.Decoder) interface{} {
	var x codec.definedMap
	c.decode(d, &x)
	return x
}

func (c codec_definedMap_codec) decode(d *codecapi.Decoder, p *codec.definedMap) {
	n2 := d.StartList()
	if n2 < 0 {
		return
	}
	n := n2 / 2
	m := make(codec.definedMap, n)
	var k string
	var v bool
	for i := 0; i < n; i++ {
		k = d.DecodeString()
		v = d.DecodeBool()
		m[k] = v
	}
	*p = m
}

func init() { codecapi.Register(codec.definedMap(nil), codec_definedMap_codec{}) }
