// Code generated by the codec package. DO NOT EDIT.

package codec

import (
	"reflect"

	"github.com/jba/codec/codecapi"
)

//// map[string]bool

var map_string__bool_type = reflect.TypeOf((*map[string]bool)(nil)).Elem()

type map_string__bool_codec struct {
	codecapi.NonStruct
}

func (c *map_string__bool_codec) TypesUsed() []reflect.Type {
	return []reflect.Type{}
}

func (c *map_string__bool_codec) SetCodecs(tcs []codecapi.TypeCodec) {
}

func (c *map_string__bool_codec) Encode(e *codecapi.Encoder, x interface{}) {
	c.encode(e, x.(map[string]bool))
}

func (c *map_string__bool_codec) encode(e *codecapi.Encoder, m map[string]bool) {
	if m == nil {
		e.EncodeNil()
		return
	}
	e.StartList(2 * len(m))
	for k, v := range m {
		e.EncodeString(k)
		e.EncodeBool(v)
	}
}

func (c *map_string__bool_codec) Decode(d *codecapi.Decoder) interface{} {
	var x map[string]bool
	c.decode(d, &x)
	return x
}

func (c *map_string__bool_codec) decode(d *codecapi.Decoder, p *map[string]bool) {
	n2 := d.StartList()
	if n2 < 0 {
		return
	}
	n := n2 / 2
	m := make(map[string]bool, n)
	var k string
	var v bool
	for i := 0; i < n; i++ {
		k = d.DecodeString()
		v = d.DecodeBool()
		m[k] = v
	}
	*p = m
}

func init() {
	codecapi.Register(map[string]bool(nil), func() codecapi.TypeCodec { return &map_string__bool_codec{} })
}
